[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe" # Use LLD Linker
rustflags = [
  "-Zshare-generics=n",
  "-Zthreads=0",        # (Nightly) Use improved multithreading with the recommended amount of threads.
]